---
spot_fleet_request_config:
  iam_fleet_role: arn:aws:iam::123456789012:role/aws-service-role/spotfleet.amazonaws.com/AWSServiceRoleForEC2SpotFleet
  spot_price: '0.017'
  target_capacity: 1
  launch_specifications:
  - iam_instance_profile:
      arn: arn:aws:iam::123456789012:instance-profile/IAMProfileName
    image_id: ami-97785bed
    instance_type: t2.medium
    key_name: default
    security_groups:
    - group_id: sg-111
    subnet_id: subnet-111, subnet-222
    user_data: "<%= user_data("dev") %>"
